fix: optimize react-dom in server-entry-only projects
SyntaxError: The requested module '/node_modules/react-dom/client.js' does not provide an export named 'hydrateRoot'